function [imgbg,bg] = bgsubtract(img,radius)
%UNTITLED Summary of this function goes here
%   SUBTRACTS BACKGROUND FROM TIFF STACK
%   IMG IS THE IMAGE DATA
%   RADIUS IS THE "ROLLING BALL" RADIUS FOR BG SUBTRACTION.  THIS SHOULD BE
%   LARGER THAN THE SMALLEST FEATURE IN THE IMAGE.  IN GENERAL, THE LARGER
%   THE RADIUS, THE MORE "CORASE" THE BG ESTIMATION WILL BE, WHILE THE
%   SMALLER THE RADIUS, THE HIGHER CHANCE THAT ACTUAL SIGNAL WILL BE
%   SUBTRACTED.
% 
%   IMG1 IS THE IMAGE AFTER BACKGROUND SUBTRACTION
%   BG IS THE IMAGE BACKGROUND ESTIMATION

bg = imopen(img,strel('disk',radius));
imgbg = img-bg;